// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZyUnTz4MqGL6xKSoNgLNLQSJkycCJVwg',
    appId: '1:714403527658:web:e2ab185b8ed4565390d093',
    messagingSenderId: '714403527658',
    projectId: 'krishimitra-302d6',
    authDomain: 'krishimitra-302d6.firebaseapp.com',
    storageBucket: 'krishimitra-302d6.firebasestorage.app',
    measurementId: 'G-KKNHHL83CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBklYeynPcou3LTsDp3Gw36gMisrVppgTk',
    appId: '1:714403527658:android:63ec50468dfa35f390d093',
    messagingSenderId: '714403527658',
    projectId: 'krishimitra-302d6',
    storageBucket: 'krishimitra-302d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPtP6rqsvSV1WtHmvRKKVFXH34bb3MxLM',
    appId: '1:714403527658:ios:2d4229b96b9e824a90d093',
    messagingSenderId: '714403527658',
    projectId: 'krishimitra-302d6',
    storageBucket: 'krishimitra-302d6.firebasestorage.app',
    iosBundleId: 'com.example.krishiMitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPtP6rqsvSV1WtHmvRKKVFXH34bb3MxLM',
    appId: '1:714403527658:ios:2d4229b96b9e824a90d093',
    messagingSenderId: '714403527658',
    projectId: 'krishimitra-302d6',
    storageBucket: 'krishimitra-302d6.firebasestorage.app',
    iosBundleId: 'com.example.krishiMitra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZyUnTz4MqGL6xKSoNgLNLQSJkycCJVwg',
    appId: '1:714403527658:web:addec26e447f1aa890d093',
    messagingSenderId: '714403527658',
    projectId: 'krishimitra-302d6',
    authDomain: 'krishimitra-302d6.firebaseapp.com',
    storageBucket: 'krishimitra-302d6.firebasestorage.app',
    measurementId: 'G-4D6M4FKEQV',
  );
}
